"""empty message

Revision ID: d8609a788a2a
Revises: e56e297e3631
Create Date: 2022-09-22 02:12:32.404818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8609a788a2a'
down_revision = 'e56e297e3631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('nombre', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'nombre')
    # ### end Alembic commands ###
